### ISSUE TITLE
multiple SLF4J bindings

### ISSUE THREAD

**Issue by Seb-Leb** [bzhanglab/PepQuery#14]
I am running pepquery 1.2.0 on an HPC platform using many cpus to search many mgf files at the same time. Sometimes the process completes with no problems but many of them show the following message and get stuck:

...
Finished proteins:140000
Finished proteins:141000
Protein sequences:141748
2019-10-25 14:27:24 [ INFO] Time elapsed: 2.23 min
Peptides with matched spectra: 2
pool-3-thread-1 -> Start 1: TDTMEYFISPRCDMDYFSLGHKCLQQLVFDR ...
pool-3-thread-2 -> Start 2: GQSLRPCTWLPEEWVLELLCTDTDLEERQGR ...
pool-3-thread-2 -> Finished 2: GQSLRPCTWLPEEWVLELLCTDTDLEERQGR .
pool-3-thread-1 -> Finished 1: TDTMEYFISPRCDMDYFSLGHKCLQQLVFDR .
All spectra have been exported to file: /nfs3_ib/ip32-ib/home/sleblanc/PepQ_BCAC_snpeff/TCGA_A2-A0YF_BH-A0DD_BH-A0E9_117C_P_BI_20131104_H-PM_f04//psm_rank.mgf
The number of spectra that need to be validated by PTM searching: 1
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/group/tools/PepQuery_v1.2.0/lib/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/group/tools/PepQuery_v1.2.0/lib/logback-classic-1.0.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
All modifications in unimod:1375
Use enzyme:Trypsin 

What should I do about this?

**Comment by wenbostar** [comment]
This message is from a library I used in unrestricted modification searching step. That has no effect on the identification result and you can ignore that. If there is no PSM needed to be validated (p-value<=0.01) using unrestricted modification searching, you will not see the message. The unrestricted modification searching step is usually the most time-consuming step especially when you get a lot of PSMs with p-value <= 0.01 in step 4 showing in this figure: [figure 2](https://genome.cshlp.org/content/29/3/485/F2.expansion.html).

> All spectra have been exported to file: /nfs3_ib/ip32-ib/home/sleblanc/PepQ_BCAC_snpeff/TCGA_A2-A0YF_BH-A0DD_BH-A0E9_117C_P_BI_20131104_H-PM_f04//psm_rank.mgf
**The number of spectra that need to be validated by PTM searching: 1**
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/group/tools/PepQuery_v1.2.0/lib/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/group/tools/PepQuery_v1.2.0/lib/logback-classic-1.0.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
All modifications in unimod:1375
Use enzyme:Trypsin

In this specific case, there is one PSM with p-value <= 0.01 so that it's needed to be further validated using unrestricted modification searching when you set -um.

**Comment by Seb-Leb** [comment]
Ok thank you I will try again with longer wall time
