### ISSUE TITLE
General Questions about PepQuery: Small bacterial proteoms, unrestricted modification search

### ISSUE THREAD

**Issue by PTK-kiel** [bzhanglab/PepQuery#28]
Hi, I have some general question about the application of PepQuery for the validation of novel peptides. 

1)	I was wondering if it is useful to use the unrestricted modification search for a organism, which had only about ~3000 predicted genes. Moreover, compared with human proteome, the proteome of a bacteria organism should be much less complex due to less modifications. I was afraid if it will increase false negative results, if we use unrestricted modifications. Do you think for bacteria it is useful to use PepQuery with open modification search  for small bacteria proteoms to validate new peptides? 

2)	Just to clarify: What does “unrestricted modification search” means? Are this really all possible modifications (with all mass shifts) or are only the PTM list with the 159 PTMs considered? Do you think (in particular for organism with less expected posttranslational modifications, e.g. bacteria) it is useful to do a “restricted modification search” with for example the 20 most abundant known modifications + artefacts ? 

3)	It is for complex proteome samples very usual to have co-isolated peptides in the MS2 spectra. How PepQuery deals with theses spectra? For example, if a “new” peptide co-eluted with a peptide from a reference protein (with a high isolation interference of maybe 70 %) the spectra will potentially better match to the reference peptide and not to the new peptide. Will PepQuery reject the “new peptide”, because the reference peptide matched better to the spectra (despite this is due to co-elution)? 

4)	The Number of random peptides generated due to the p-value calculation is dependent on the peptide size. Is this a problem for short peptides (6-8 AS) (is there the p-Value calculation reliable?)?

**Comment by wenbostar** [comment]
> 2. Just to clarify: What does “unrestricted modification search” means? Are this really all possible modifications (with all mass shifts) or are only the PTM list with the 159 PTMs considered? Do you think (in particular for organism with less expected posttranslational modifications, e.g. bacteria) it is useful to do a “restricted modification search” with for example the 20 most abundant known modifications + artefacts ?

We use all modifications (~1000) from Unimod database (http://www.unimod.org/). More information about "unrestricted modification search" can be found in the method section ["Competitive filtering based on unrestricted modification searching" of the paper](https://genome.cshlp.org/content/29/3/485.full). For bacteria, I think this is still useful. As you can see in this study: https://www.pnas.org/content/pnas/111/52/E5633.full.pdf, a lot of PTMs can be found in a model cyanobacterium, Synechococcus 7002. When we get a better match (a peptide from reference database with a modification from Unimod) from the unrestricted modification search for a spectrum, it doesn't mean this spectrum is really from the peptide matched from the unrestricted modification search. Even the match is not a correct match, it is still useful because it may indicate the original match is a false match. This is similar to the p-value filtering based on random sequences.

**Comment by wenbostar** [comment]
> 3. It is for complex proteome samples very usual to have co-isolated peptides in the MS2 spectra. How PepQuery deals with theses spectra? For example, if a “new” peptide co-eluted with a peptide from a reference protein (with a high isolation interference of maybe 70 %) the spectra will potentially better match to the reference peptide and not to the new peptide. Will PepQuery reject the “new peptide”, because the reference peptide matched better to the spectra (despite this is due to co-elution)?

This really depends on the fragments and their relative intensities for each peptide from the chimeric spectrum. If most of the fragments with relatively high intensity are from the matched novel peptide, the chance of getting rejected due to the higher match to another peptide with elution will be low. Otherwise, it may be rejected.




> 4. The Number of random peptides generated due to the p-value calculation is dependent on the peptide size. Is this a problem for short peptides (6-8 AS) (is there the p-Value calculation reliable?)?

You're right that the number of random peptides generated for an input peptide depends on the length of the peptide. In PepQuery, we have a few steps to filter potential false positives, including (1) competitive filtering based on reference sequences; (2) statistical evaluation (p-value); and (3) competitive filtering based on unrestricted modification searching. If a peptide with length less than 8 amino acid gets a match that passed all these filters, the chance of this match is a false positive will be very low. But if you're not confident about this identification, you can further check the quality of the match using [PDV](https://github.com/wenbostar/PDV) or use retention time-based quality evaluation that we used in a recent study: [_Nature Communications 11, Article number: 1759 (2020)_](https://www.nature.com/articles/s41467-020-15456-w).

**Comment by PTK-kiel** [comment]
Thank you very much for your detailed answers!
