### ISSUE TITLE
-1 value appearing in n_ptm, n_random, and total_random

### ISSUE THREAD

**Issue by Seb-Leb** [bzhanglab/PepQuery#5]
What is the meaning of -1 in some of the rows in the n_ptm, n_random, and total_random of the output file psm_rank.txt?
Thank you

**Comment by wenbostar** [comment]
If the value is -1 in any of the three columns for a PSM, it means that this identification is not confident. Specifically, if the values of **n_random** and **total_random** are -1 for a PSM, it means there is at least one better match found in step 3 "competitive filtering based on reference sequences" (see Figure 2 of [PepQuery paper](https://genome.cshlp.org/content/29/3/485.long) for details) so that it's not necessary to perform step 4 (n_random=-1, total_random=-1, and n_ptm=-1). If only the value of n_ptm is -1 for a PSM, it means the p-value is less than 0.01 so that it's not necessary to perform step 5 (n_ptm=-1).

**Comment by Seb-Leb** [comment]
Perfect, thank you!
