### ISSUE TITLE
Interpretation of psm_rank.txt file

### ISSUE THREAD

**Issue by anuC** [bzhanglab/PepQuery#67]
Hi Bo,

I was looking for a way to interpret the values in some of the columns in psm_rank.txt file and wonder there is a detailed documentation for these numbers, other than the one given  in the [http://www.pepquery.org/document.html](url).

At present, I am more interested in,

1. Column with header 'modification'. For e,.g, in 'Phosphorylation of S@10[79.9663]', what the value of 79.9663 actually stands for?
2. Column with header 'rank'. What is the meaning of rank 1 for a specific peptide sequence?
3. How to interpret the value of '-1' in column 'n_ptm'?

Any help would be highly appreciated

Thanks in advance
Anu

**Comment by wenbostar** [comment]
Hi Anu,

> Column with header 'modification'. For e,.g, in 'Phosphorylation of S@10[79.9663]', what the value of 79.9663 actually stands for?

The value of 79.9663 is the modification mass added to a specific amino acid. In this case, it is on the 10th amino acid S.

> Column with header 'rank'. What is the meaning of rank 1 for a specific peptide sequence?

Two or more targeted peptides may be matched to the same spectrum. These matches will be ranked based on their scores and the one with highest score will rank as 1. 

> How to interpret the value of '-1' in column 'n_ptm'?

"-1" means that there is no unrestricted modification searching done for this match because it fails in a previous validation step.

Bo

**Comment by anuC** [comment]
Thank you Bo, for the details.
