### ISSUE TITLE
warnings upon running pepquery with unrestricted modification searching

### ISSUE THREAD

**Issue by VladimirRoudko** [bzhanglab/PepQuery#9]
Hello,

I am testing standalone pepquery on Linux machine through running several commands with different parameters.  I noticed some inconsistencies in the output and strange warnings in stderr. 
Machine configuration:
OS: Ubuntu 18.04.3 LTS (Bionic Beaver)
Linux kernel: 4.15.0-64-generic
Java: openjdk 11.0.4 2019-07-16, OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)

Each command uses one *.mgf file stored in ${fbn}. list of peptides is stored in file $PEPTIDE. Indexed human proteome is stored in $PDB. Here are the three commands:
1. pepquery -o "pep" -prefix "pep" -t 1 -ms "${fn}" -pep "$PEPTIDE" -db "$PDB" -n 1000 -m 1 -maxLength 50 -minLength 7 -um -hc FALSE -cpu 10
2. pepquery -o "pep" -prefix "pep" -t 1 -ms "${fn}" -pep "$PEPTIDE" -db "$PDB" -n 1000 -m 1 -maxLength 50 -minLength 7 -um -hc TRUE -cpu 10
3. pepquery -o "pep" -prefix "pep" -t 1 -ms "${fn}" -pep "$PEPTIDE" -db "$PDB" -n 1000 -m 1 -maxLength 50 -minLength 7 -cpu 10

 when I run ".1" and ".2", I get the following in stderr:

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/mnt/modules/pepquery/1.2.0/lib/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/mnt/modules/pepquery/1.2.0/lib/logback-classic-1.0.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1 (file:/mnt/modules/pepquery/1.2.0/lib/jaxb-impl-2.2.4-1.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

"3" does not give any stderr.

Does this imply, that validation with unrestricted modification "-um" does not work? 

Also, I have no difference between my output files ("psm_rank.txt") upon running "1", "2" or "3", which is a bit strange as "3" does not use "-um" at all.

Finally, in my "psm_rank,txt" I am getting many peptides with p-value = 100. Is it a bug?

Thank you.
Vladimir

**Comment by VladimirRoudko** [comment]
Just FYI: pepquery version is 1.3.0

**Comment by wenbostar** [comment]
Hi Vladimir, thanks for your interest in PepQuery. 

This warning message was from the Java libraries used in PepQuery (unrestricted modification searching step). I don't think that has an impact on the specific functions from the JAVA libraries used by PepQuery. You can ignore this warning message. So when you see this message, it doesn't mean that the unrestricted modification searching (-um) doesn't work in your analysis.

> Also, I have no difference between my output files ("psm_rank.txt") upon running "1", "2" or "3", which is a bit strange as "3" does not use "-um" at all.

First of all, this is possible. As you can see the description of PepQuery algorithm in the [PepQuery paper](https://genome.cshlp.org/content/29/3/485.full), the PepQuery workflow involves five major steps: (1) target peptide sequence preparation and initial filtering; (2) candidate spectra retrieval and PSM scoring; (3) competitive filtering based on reference sequences; (4) statistical evaluation; and (5) competitive filtering based on unrestricted post-translational modification searching. If the p-value calculated from step (4) for a PSM is <= 0.01, unrestricted modification searching (step 5) will be used to further validate the PSM when -um is used. However, if the p-value is > 0.01, it means the PSM is not confident and the further validation by unrestricted modification searching for this PSM is not necessary at all even -um is used. So if none of the PSMs has a p-value <= 0.01, you will have the same outputs for "1", "2" and "3".

> Finally, in my "psm_rank,txt" I am getting many peptides with p-value = 100. Is it a bug?

This is not a bug. I'm sorry the output is not self-explaining. When the p-value is 100 for a PSM, it means we find at least one better match for the spectrum from step (3). In this case, the PSM is not confident so that PepQuery is not necessary to perform step (4) and step (5) evaluations for this PSM.

I'm happy to help you use PepQuery. Please feel free to let me know if you any other questions.

**Comment by VladimirRoudko** [comment]
Dear Bo,

thank you for your prompt response! All the explanations are very useful. I am new to proteomics, so sorry in advance for some naive questions.

Concerning the p-value threshold: indeed, in the original paper (genome_research_2019) you used p-value = 0.01 cutoff. What is the reasoning to use 1% FDR instead 5% (assuming p-value 0.05 as a conventional cutoff in majority of the stat)?

Thank you!
Vladimir

**Comment by wenbostar** [comment]
We found that we could achieve a good balance between sensitivity and specificity with the cutoff of p-value <= 0.01. The cutoff of 0.05 is a bit loose in this analysis.

**Comment by wenbostar** [comment]
I recommend you to use the default cutoff (p-value<=0.01) when you use PepQuery for validation of novel peptide identification.

**Comment by VladimirRoudko** [comment]
Thanks a lot, that's very helpful!
